---
abstract: 'Perl Distribution Creation Toolkit'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::LongString: 0.11
  Test::More: 0.86
  Test::Script: 1.03
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist
name: Perl-Dist
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Archive::Tar: 1.42
  Archive::Zip: 1.26
  CPAN: 1.9301
  File::Copy::Recursive: 0.38
  File::Find::Rule: 0.30
  File::HomeDir: 0.82
  File::Path: 2.07
  File::PathList: 1.04
  File::Remove: 1.42
  File::ShareDir: 1.00
  File::Spec: 3.29
  File::Temp: 0.21
  File::pushd: 1.00
  HTTP::Status: 5.817
  IO::Capture: 0.05
  IPC::Run3: 0.042
  LWP::Online: 1.07
  LWP::UserAgent: 5.823
  LWP::UserAgent::WithCache: 0.06
  Module::CoreList: 2.17
  Object::Tiny: 1.06
  PAR::Dist: 0.42
  Params::Util: 0.35
  Portable::Dist: 0.02
  Probe::Perl: 0.01
  Process: 0.22
  Process::Delegatable: 0.22
  Process::Storable: 0.22
  Template: 2.20
  YAML::Tiny: 1.36
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.12
