---
abstract: 'Perl Distribution Creation Toolkit'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::LongString: 0.11
  Test::More: 0.86
  Test::Script: 1.03
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.83'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist
name: Perl-Dist
no_index:
  directory:
    - inc
    - share
    - t
requires:
  CPAN: 1.9301
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Perl-Dist
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Perl-Dist
version: 1.14
