---
abstract: 'Perl Distribution Creation Toolkit'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::LongString: 0.11
  Test::More: 0.80
  Test::Script: 1.03
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist
name: Perl-Dist
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  Archive::Tar: 1.38
  Archive::Zip: 1.25
  CPAN: 1.93
  File::Copy::Recursive: 0.37
  File::Find::Rule: 0.30
  File::HomeDir: 0.81
  File::Path: 2.04
  File::PathList: 1.04
  File::Remove: 1.42
  File::ShareDir: 1.00
  File::Spec: 3.2701
  File::Temp: 0.20
  File::pushd: 1.00
  HTTP::Status: 5.817
  IO::Capture: 0.05
  IPC::Run3: 0.042
  LWP::Online: 1.07
  LWP::UserAgent: 5.817
  LWP::UserAgent::Determined: 1.03
  Module::CoreList: 2.15
  Object::Tiny: 1.06
  PAR::Dist: 0.37
  Params::Util: 0.33
  Portable::Dist: 0.02
  Probe::Perl: 0.01
  Process: 0.22
  Process::Delegatable: 0.22
  Process::Storable: 0.22
  Template: 2.20
  YAML::Tiny: 1.32
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.06
