---
abstract: 'Perl Distribution Creation Toolkit'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Probe::Perl: 0.01
  Test::LongString: 0
  Test::More: 0.42
  Test::Script: 1.02
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist
name: Perl-Dist
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  Archive::Tar: 1.34
  Archive::Zip: 1.20
  CPAN: 1.9205
  File::Copy::Recursive: 0.25
  File::Find::Rule: 0.30
  File::Path: 1.08
  File::Remove: 0.37
  File::ShareDir: 0.99
  File::Spec: 3.17
  File::Temp: 0.20
  File::pushd: 0.32
  HTTP::Status: 1.28
  IO::Capture: 0.05
  IPC::Run3: 0.034
  LWP::Online: 0.03
  LWP::UserAgent: 2.033
  LWP::UserAgent::Determined: 0
  Module::CoreList: 2.13
  Object::Tiny: 1.02
  PAR::Dist: 0.25
  Params::Util: 0.25
  Portable::Dist: 0.02
  Process: 0.20
  Process::Delegatable: 0
  Process::Storable: 0
  Tie::File: 0
  Tie::Slurp: 0.03
  YAML::Tiny: 1.12
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.04
